export const MOTIVATION_LIST_REQUEST = 'MOTIVATION_LIST_REQUEST'
export const MOTIVATION_LIST_SUCCESS = 'MOTIVATION_LIST_SUCCESS'
export const MOTIVATION_LIST_FAIL = 'MOTIVATION_LIST_FAIL'

export const MOTIVATION_DETAILS_REQUEST = 'MOTIVATION_DETAILS_REQUEST'
export const MOTIVATION_DETAILS_SUCCESS = 'MOTIVATION_DETAILS_SUCCESS'
export const MOTIVATION_DETAILS_FAIL = 'MOTIVATION_DETAILS_FAIL'

export const MOTIVATION_DELETE_REQUEST = 'MOTIVATION_DELETE_REQUEST'
export const MOTIVATION_DELETE_SUCCESS = 'MOTIVATION_DELETE_SUCCESS'
export const MOTIVATION_DELETE_FAIL = 'MOTIVATION_DELETE_FAIL'

export const MOTIVATION_CREATE_REQUEST = 'MOTIVATION_CREATE_REQUEST'
export const MOTIVATION_CREATE_SUCCESS = 'MOTIVATION_CREATE_SUCCESS'
export const MOTIVATION_CREATE_FAIL = 'MOTIVATION_CREATE_FAIL'
export const MOTIVATION_CREATE_RESET = 'MOTIVATION_CREATE_RESET'

export const MOTIVATION_UPDATE_REQUEST = 'MOTIVATION_UPDATE_REQUEST'
export const MOTIVATION_UPDATE_SUCCESS = 'MOTIVATION_UPDATE_SUCCESS'
export const MOTIVATION_UPDATE_FAIL = 'MOTIVATION_UPDATE_FAIL'
export const MOTIVATION_UPDATE_RESET = 'MOTIVATION_UPDATE_RESET'