export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_PASSWORD_RESET_EMAIL_REQUEST = 'USER_PASSWORD_RESET_EMAIL_REQUEST'
export const USER_PASSWORD_RESET_EMAIL_SUCCESS = 'USER_PASSWORD_RESET_EMAIL_SUCCESS'
export const USER_PASSWORD_RESET_EMAIL_FAIL = 'USER_PASSWORD_RESET_EMAIL_FAIL'

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST'
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS'
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL'

export const USER_ADD_ACTIVITY_TO_BUCKET_REQUEST = 'USER_ADD_ACTIVITY_TO_BUCKET_REQUEST'
export const USER_ADD_ACTIVITY_TO_BUCKET_SUCCESS = 'USER_ADD_ACTIVITY_TO_BUCKET_SUCCESS'
export const USER_ADD_ACTIVITY_TO_BUCKET_FAIL = 'USER_ADD_ACTIVITY_TO_BUCKET_FAIL'

export const USER_REMOVE_ACTIVITY_FROM_BUCKET_REQUEST = 'USER_REMOVE_ACTIVITY_FROM_BUCKET_REQUEST'
export const USER_REMOVE_ACTIVITY_FROM_BUCKET_SUCCESS = 'USER_REMOVE_ACTIVITY_FROM_BUCKET_SUCCESS'
export const USER_REMOVE_ACTIVITY_FROM_BUCKET_FAIL = 'USER_REMOVE_ACTIVITY_FROM_BUCKET_FAIL'

export const USER_ADD_ACTIVITY_TO_TODO_REQUEST = 'USER_ADD_ACTIVITY_TO_TODO_REQUEST'
export const USER_ADD_ACTIVITY_TO_TODO_SUCCESS = 'USER_ADD_ACTIVITY_TO_TODO_SUCCESS'
export const USER_ADD_ACTIVITY_TO_TODO_FAIL = 'USER_ADD_ACTIVITY_TO_TODO_FAIL'

export const USER_REMOVE_ACTIVITY_FROM_TODO_REQUEST = 'USER_REMOVE_ACTIVITY_FROM_TODO_REQUEST'
export const USER_REMOVE_ACTIVITY_FROM_TODO_SUCCESS = 'USER_REMOVE_ACTIVITY_FROM_TODO_SUCCESS'
export const USER_REMOVE_ACTIVITY_FROM_TODO_FAIL = 'USER_REMOVE_ACTIVITY_FROM_TODO_FAIL'

export const USER_ADD_ACTIVITY_TO_COMPLETED_REQUEST = 'USER_ADD_ACTIVITY_TO_COMPLETED_REQUEST'
export const USER_ADD_ACTIVITY_TO_COMPLETED_SUCCESS = 'USER_ADD_ACTIVITY_TO_COMPLETED_SUCCESS'
export const USER_ADD_ACTIVITY_TO_COMPLETED_FAIL = 'USER_ADD_ACTIVITY_TO_COMPLETED_FAIL'

export const USER_ADD_ACTIVITY_TO_ARCHIVE_REQUEST = 'USER_ADD_ACTIVITY_TO_ARCHIVE_REQUEST'
export const USER_ADD_ACTIVITY_TO_ARCHIVE_SUCCESS = 'USER_ADD_ACTIVITY_TO_ARCHIVE_SUCCESS'
export const USER_ADD_ACTIVITY_TO_ARCHIVE_FAIL = 'USER_ADD_ACTIVITY_TO_ARCHIVE_FAIL'
